# Generated by Django 4.0.1 on 2022-01-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_alter_country_code'),
        ('course', '0002_remove_course_n_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Dolar'), ('PEN', 'Soles')], default='PEN', max_length=3)),
                ('state', models.CharField(choices=[('active', 'Activo'), ('done', 'Terminado'), ('cancel', 'Cancelado')], max_length=16)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_ids', to='partner.partner')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_ids', to='partner.student')),
            ],
        ),
    ]
