# Generated by Django 4.0.1 on 2022-01-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_enrollment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
    ]
