# Generated by Django 4.0.1 on 2022-01-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_enrollment_course_enrollment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='n_invoice',
            field=models.CharField(default='', max_length=16),
        ),
    ]
