# Generated by Django 4.0.1 on 2022-01-16 15:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_enrollment_n_invoice'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enrollment',
            managers=[
                ('enrollment_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
