# Generated by Django 4.0.1 on 2022-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_email_partner_last_name_partner_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('second_last_name', models.CharField(default='', max_length=64)),
                ('phone', models.CharField(default='', max_length=16)),
                ('email', models.CharField(default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
