# Generated by Django 4.0.1 on 2022-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_country_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
