# Generated by Django 4.0.1 on 2022-01-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_alter_documenttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.documenttype'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.documenttype'),
        ),
    ]
