# Generated by Django 4.0.1 on 2022-01-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_country_partner_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='document_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='document_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='partners',
            field=models.ManyToManyField(to='partner.Partner'),
        ),
    ]
