# Generated by Django 4.0.1 on 2022-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_partner_document_number_student_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='partners',
            field=models.ManyToManyField(related_name='students', to='partner.Partner'),
        ),
    ]
