# Generated by Django 4.0.1 on 2022-01-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_alter_student_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
